plugins:
  - "@dotcom-tool-kit/component"
  - "@dotcom-tool-kit/mocha"
  - "@dotcom-tool-kit/eslint"
  - "@dotcom-tool-kit/lint-staged-npm"
hooks:
  test:local:
    - Eslint
    - Mocha
  test:ci:
    - Eslint
    - Mocha
options:
  "@dotcom-tool-kit/circleci":
    nodeVersion:
      - '18.16'
      - '16.20'
